version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=netbox"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
